# Site settings
title: Jan Milosh
email: janmilosh@gmail.com
description: "Full-Stack Developer"
baseurl: ""
url: "https://janmilosh.com"
twitter_username: janmilosh
github_username:  janmilosh
paginate: 5

# Build settings
markdown: kramdown
permalink: /:title.html

plugins: [jekyll-paginate]
